[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
werewolf_saga = "J3HhUaKjMaC71xyJLGmu31BR5KdE1osVyFmKCngBqAzH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vincentleow/.config/solana/werewolfsaga.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
